input {
  tcp {
    port => 5044
  }
}

filter {
  grok {
    match => {
      "message" => [
        "%{IP:ip} - - \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{URIPATH:uri} HTTP/%{NUMBER:version}\" %{NUMBER:status} %{NUMBER:bytes}"
      ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "api-logs-direct"
  }
  stdout {}
}
