input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["full-pipeline"]
    codec => "plain"
  }
}

filter {
  grok {
    match => {
      "message" => [
        "%{IP:ip} - - \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{URIPATH:uri} HTTP/%{NUMBER:version}\" %{NUMBER:status} %{NUMBER:bytes}",
        "%{GREEDYDATA:json}"
      ]
    }
  }

  json {
    source => "message"
    skip_on_invalid_json => true
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "api-logs-full"
  }
  stdout {}
}
