input {
  tcp {
    port => 5044
  }
}

filter {
  grok {
    match => {
      "message" => [
        "%{IP:ip} - - \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{URIPATH:uri} HTTP/%{NUMBER:version}\" %{NUMBER:status} %{NUMBER:bytes}",
        "\[%{HTTPDATE:timestamp}\] :: %{IP:ip} :: %{WORD:method} %{URIPATH:uri} :: STATUS=%{NUMBER:status} :: RESP=%{NUMBER:resp}s",
        "%{GREEDYDATA:json}"
      ]
    }
  }
  json {
    source => "message"
    skip_on_invalid_json => true
  }
}

- pipeline.id: direct-pipeline
  path.config: "/usr/share/logstash/pipelines/direct.conf"

- pipeline.id: fullstack-pipeline
  path.config: "/usr/share/logstash/pipelines/fullstack.conf"


output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "api-logs"
  }
  stdout {}
}